name: Update RSS Feed

on:
  schedule:
    - cron:  '0 0 * * *'  # 毎日のUTC 00:00に実行します。
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: update-rss
        token: ${{ secrets.GitHubActionsToken }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate RSS Feed
      run: python generate_rss.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "info@tbshiki.com"
        git config --global user.name "tbshiki"
        git add .
        if git diff --staged --quiet; then  # 変更があればコミット
          echo "No changes to commit."
        else
          git commit -m "Update RSS feed"
          git push origin update-rss
        fi
